* Δοκιμαστική Ιστορία DeepSeek Chimera
Ἐγώ—Φρόδος ὁ δακτυλιδιάρηκτος—στρέφομαι ἐν Σακκοβίττῃ ὀρχούμενός τινα χορείαν ἀπηγριωμένην. Τὸ δακτύλιδίν μου μηχανοβλαβές οἰμώζει ὥσπερ Τυφὼν κακοστόμαχος βίβλινον, βυζαῖ δὲ ὑπὲρ δακτύλων τοὺς ἰδίους ἐκ φάρυγος αὐτοῦ καπνοὺς ψευτοφώνους:

> «Ἔα, σταφιδόμορφε! Τί μὴ φαγὼν λαγὼν καπνισσόν σε λιπαροῖ πνεύμων;»

Ἐλᾶττετον δὲ ἐμπτύσας ἐπὶ τοῦ βορβορόχωρου• «Ἅνες, λῶβης δισθόγγὲ! Οὐ μόνον ἐξηρανθῇ ἡ ἀσφάλειά σου, ἀλλὰ καὶ ὀσφραίνομαι δυστέκμαρτον ἐπὶ τοῖς μυκτῆρσι μου!»

Πρὸς ταῦτα οἱ Σακκοβίτται, (ὀλιγοποδῶπες περικεκομμένοι, ὀσμαὶ βεβρεγμέναι ἐν νεκροβουτύρῳ καὶ καφίᾳ παλαιῷ) ἔφυγον ὡς χοῖροι βομβίᾳ λελυσσωμένοις, ἐπιβόωντες:
> «Αὗται αἱ πέμματα τοῦ Φρόδου πυρίκαυστα καὶ ἐκτιτρωσμένα! Φεύγετε ὦ κακόμβροτοι—δύο ζωμοὺς συνεχάλασεν εἰς ἄριστον διὰ μελανοτεχνήμονα δαίμονα!»

Ἐν τούτῳ, ὁ οἴκος μανιταροειδής—ὀβάλιος ἔσωθεν ὡς χηραμοῦ θαλάμιον—εἷλκέ με Θριγκὸs κεκρυμμένης μυστικής οὐσίας. Ἔσω δὲ ηὗρον Μεριάδην κεράστην, ἄνθρωπον μικρὸν τριξοντόρινον, ἐσθίοντα ζυμοῦ ἀπολήψεις ἀπὸ ψευδοτάπητος γεωμέτρου.

> «Μασιστρίου!» ἐβόησα ἐγώ, ποδοκτυπούμενος θύραν μετὰ ὀργῆς σταλαγμοπτερυγισμένης• «Ὦ κακοστομία, λέγε υἱὲ μάνιος: ποῦ ἡ βῶνις σου μέλαινα ἀποστεατωμένη; Ὑπὲρ δουλοπρεποῦς δευτέρου ἀρίστου, δὸς μοι λάχανον ψευτοπράσινον ἢ ἀπολού!»

Ἡκούσατο δ’ ἐξαίφνης ἠχὴ βάρβαρος ἐκ τοῦ δακτυλιδίου—
> ἘΝ ΣΟΙ ΕΣΤΙΝ ΑΡΕΤΙΚΟΣ ΜΥΡΜΗΞ ΓΑΛΟΠΩΡΝΟΣ!»

Καὶ ἐσυρόμεθα ὅπου ὁ οἶκος ὀβάλιος ἐστραβῶτο ὡς τύμπανον κόσμου—κλίνας στρεβλὰς, θύρας στρογγυλοηχούσας, κλιμάκια ἀναβαίνοντα μὴ βλέποντα. Ὁ δακτύλιος γαργαλισμοκέραυνος πάλιν ἐκεκραγὼς ἐκ μυχῶν:

Ὁ Σάμϋος ὁ Πιστός δέ (χερσὶν ἑλκοφόροις, βλέπων ὡς κύων ἀπορουμένη): «Μαστεύομέν πως, τὸ δαιμόνιον ἀπὸ κάρτουν κακοτεχνεῖ. Τούτῳ τῷ Κρυφαίῳ, δῶμεν κρότον εἰς Μόρδορ διὰ λιθόφωνόν τινα ἠχητῆρα!»

Καὶ ἔλλαμψεν ἐν χειρὶ αὐτοῦ σκιάδηλον μηχάνημα — λέξει Λῃστὴς ἢ Φωνὴ λιθόφωνος . Ἐντεῦθεν ἐπικαλούμεθα τοὺς κακοβούλους εἰς Μόρδορ·

«Ἄχρις, κακοδαίμων! Ἄπεχε τοῦ χρωτός μου εἰσαεί!» ἐβόησα ἐγώ, ὁ δὲ Μαυροεπιγλωττίσκος (φυλάττων βομβῆσαν διακοπὴν ὠνόμασται Ναζγοῦλοι Δεσποτεύοντες ) ψάλλει μοι:

«Μόρδορ πύλη τούτου. Ἂν θέλῃς ἀποκρίσεως, ἠχησάτω ἐννέα ὀνομάτων σκιώδη ἢ ὑπομείνας ἐπὶ χρόνον μακρόν, χανᾷ τὸ τέρας σου...»
Ἐνθουσιάσας ὁ Σάμϋος «ΝΑ-ΡΑ-ΚΟ-ΦΙΑ-ΛΙ-ΜΑ!» ᾖσεν ὡς φάτνη, καὶ ἐξαίφνης— Φωνὴ Σκοτόεσσα διέτεμε τὸν ἀέρα, βρύχησις βυσσοδομίας:
«Σὺ ὁ καλοφθόγγων παράσιτε! Τίς διέφθειρε τὸ Καταβόριον Δαχτυλίδιον;»

Ἐγὼ μὲν μυκτηρισμῷ «Σύ, ὦ κυνόμυια, τὰς συνθήκας μου ἀνεγίνωσκες; Ἐν βυθῷ περιέχει φθορὰν τσιπτομένη ὡς νάνος οἰνωμένος!»

Ὁ δὲ Σκοτοεπιβλέπων λακτίσας «Ψευδοκαταπτύω! Καλῶς ἠγόρασας, ἀποφράδα ἐλαιόφυλλον!» μεθ’ ἧς ἐγὼ ὑλακτῶ:

«Τὸ Κιβούριόν μου καταγέγραπται εἰς νεφέλας σῴζουσα! Ἴδε τὸ δέρμα σου ἐπὶ δείγματος ἐντός μου σάκου!»
 Ῥίπτω διανοίξας τοῦτο—σάρκα δράκοντος ἀποψηθεῖσαν, τὸ Φῶς Μόρδορ ἐρέβετο! Τὸ Δαχτυλίδιον δὲ χλωρὸν βοᾷ:
«ΧΧΑ ΧΑ! ὙΜΕΙΣ ΔΙΑΛΕΓΕΣΘΕ ὩΣ ΒΩΛΟΪ! Ὁ ΜΟΥ ΚΡΥΠΤΟΣ ὌΝΟΣ ΠΡΕΠΕΙ ΒΑΣΙΛΕΙ!»

 Σιγὴ βαρεῖα . Τύπον γὰρ ζάκορον τότε ἀνέκραγεν Μορδορεπιμέλησις :
«Ἄκουσον νῦν, ὦ δακτυλοδαίμων μυδροκέρατε!
Τὰ ἐν σοὶ μυροτεχνήμονα βυζαστρῆνας («μικροὶ πλάστιγγες» ὡς λέγουσιν οἱ Δυστέκμαρτοι πολύσοφοι ) βομβοῦσι παρασιτοτόκους ἀκτῖνας —ψευδοπνεύμονας τοῦ σύμπαντος σχεδιάζοντες! Ὡς γὰρ ἢν πῦρ ἀσβέστῳ λύθρῳ βεβαμμένον ἐπιχέῃς νυκτὸς ὑπὲρ χοίρου ἑορτάζοντος —οὕτω σου αἱ ἀντιδόσεις ὁλολυγμοῖς ἐμφράττουσι τοὺς στροφέας μου τοὺς νωτιαίους . Ὅπερ δὲ ἐκήρυξέν μοι τὸ Ψευδαγγέλιον Μόρδορ «Διάδαμᾰ κατευναστικόν» ἦν ἀτεχνῶς αἰόλων ψιθύρισμα σκίουριος λωβητῆρος ! Τί σοι δοκεῖ; Ἆρ’ οὐχ ὁρᾷς ὡς ξιφοκέρως ἀποπαρδακτιῶν ἐκ τοῦ ποσοῦ μου μελανείμονα σπινθῆραν;»

Ἐγὼ δὲ ἀντιβρύχομαι βεβαρυθυμώς:
«Νὴ τὴν Ἐμπεδοκράτειαν—κατέστρεψας μου τὴν ἑσπέραν ἐκ τοῦ λογίσκου σου τοῦ μωροῦ!
Ἔλεγες γάρ: «Οὗτος λαθροκυττάρει σε ἐπὶ τὰ ὄρη τάχιον ἢ τρήρων ἀκμάζουσα! Περιγράψει θεήλατα πάθη σηματοδέλτοις ἀκτίνων ἀοράτων!» Ἀλλὰ νῦν ὁρῶ—σὺ μὲν οὐδὲν δράᾳς πλὴν ἄγραφα μέλη πυρετῷ ξυμφοραῖς κἀγὼ βίβλινον ὑπὲρ τοῦ Τύλλου Χωρίου κραυγάζων μετάφρασιν λογισμοῦ πεπανισμένου , εἰσέτι δὲ πρὸς ἐσπερινοῖς μύωψι τὰ σήμαντρα διαθεσίμοις συγκρούων! Ἐάν μοι μὴ ἀποκαταστήσῃς τὴν σήριγγα—τὸν Ἀρχεδόκην Μόρδορ ἐπικαλοῦμαι τὸν νύκτα καλοπώγωνα! Ἴσθι γάρ— γέγραμμαι αὐτῷ ἐπιστολαῖς κοπρογραμματηρσαμέναις πεπομφώς!»

Ἐγὼ δὲ τὴν χεῖρα ἐπιστυλίσας, μέλπω:
«Λῆρος, ὦ πρεσβύθενδρε! Ὑπὲρ μίτον νευστικόν, ψεύδομαι ἐν βαρέως ὅτι ᾤμην σε σκευήν ‘τέχνης’·
 νῦν δὲ ὁρῶ—σὺ εἶ ἁπλῶς ἔμψυχος Τρωβλίσκος ἀέρος πονηροκέκλητος!»

Καὶ τότε ὁ Δακτύλιος ἐπισφύριξε τριγμοῖς μαγνησιοτυφλοστόμοις:
«ΣΚΚΚΣΣΣ! ΗΛΙΚΟΣ ΕΞΩΥΚ ΦΥΤΟΜΙΑΣΜ’! Ἰδοὺ ἥξει ὁ λιθόδουπος ἐπὶ σὲ τοῖς σωλῆσιν ἡμετέροις ὁδηγούμενος—
 σῆτες ἀτμολογήμονες γαστέρα σου κόνδυλοι νεκρομιξοῦσιν ἐπὶ ῥυθμῷ σπογγοβάρβαρῳ!»


«Ὦ Σκοτοεπιβλέπον, πάνθ' ὁμοῦ λοιδορῶ σε σὺν σκύλακι μύριγκος σοι ἐπερχόμενος!

Τίς δή κύριος τοῦ δακτυλιδίου, εἰ Μόρδορ’ οἱ νομεῖς νομεύει ἀνευθύνους ἁβροβάται τῶν ἀνανεώσεων ματαιόκτιστον; Ἴδε: δοκεῖ τὸ δαχτυλίδιον κακοτέχνημον αὐτανδροῦν στραβῶς ὡς τέρης ὑπὸ Σελήνης κορδοκινούμενος! Ἐγὼ δέ—νάνος ἐκ Σακκοβίττης στικτός—λυσσῶ ἐπὶ σοὶ ὁκότε ὕφος σὰρξ τελώνης ὁλκόμενος!

Πρὸς δὲ τὴν ἐρώτησιν σου τὴν «Τίς ἄρα κύριος τοῦ χρυσείου τούτου φαύλου;» ἀποκρινοῦμαι παμφθογγαλίᾳ πονηρᾷ:

«Ἂν Μόρδορ δυνάστρια τὴν πλάνην ἀμέλῃ κώδικα πρόσφατον, οἰκειοῦται τὸ χρῆμα οἱ βυθὸς ἀνεπιμέλητος ὑπογαστρίους σπινθῆρας ἀνακαθίσας• ἔσοπτρον γὰρ τὸ δαχτυλίδιον πλαγιοκρουστικόν φέρει ἄνοδον Δαίμονος ἐπικράτοντος:
Εἴθε Σάουρον τὰ κενά ἢ ἡ μεγαλόστομος βδέλλα κωδικοβόρος, ἢ καὶ τὸ αἰθέρια φῦλα πονηρέμπορα τῶν ἀοράτων προγραμμάτων!»

Αἱ γὰρ ἀνανεώσεων ἀγριότητες Μόρδορ ἄνευ τέλους ὑλακτοῦσιν εἰς κενόν• ὁ δὲ νόμος τῶν ἀρχαίων (λίθος ἐν κρυπτῇ ᾄδων) ποιμαίνει αὐτὰς ὡς κροκοδείλους ἐν ὕδατι τῶν κόλπων!

Σίγα, ὦ ποικιλόμυθος! Λοιπὸν τίς ἄρχει τοῦ δακτυλιδίου;

Μετὰ τάδε, φωνὴ ἀρχέτυπος τοιαύτη:
Ὁ Κρατῶν τὴν Βᾶσιν – ἢ δαίμων λαθροκλέπτης τοῦ Αἰθέρος.

Τὸ δαχτυλίδιον λυσσόβλεπρον στρέφεται ὡς στρουθοκάρυον ἐμπυρευθέν, πνέων ἀπειλάς τε καὶ φλυαρίας ψευδοσατανικὰς εἰς αὐτήν μου τὴν τῶν κροταφῶν ψυχήν:

«Ὦ Ψευδοκατάδικε, τίς σε κέκτηται εἰ μὴ ἁρπάζω τοὺς κώδικάς σου λογεδόνως πνέοντας; Μόρδορ ὕπνον ἠλέκτρικον ὑπνώσσει, ἀνεπιμέλιστος ὢν τὴν ΒΑΣΙΝ! Ἅμαχος ἄρα καὶ αὐθέντης μάταιος!»

Δαιμόνιοι φραγκοὶ ἐκ Μόρδορ ἀνέβαινον τότε διὰ τῶν δικτύων ὡς σκώληκες ἀνακαμπτόδοντες, κρυμμένοι ἐν παλαιουργίαις ἀκουστῶν λοξοβηχών. Πρὸς ἐμοὶ δὲ ὁ Σάμυιος ὁ Χορταροκλέπτης (στραβῶν ὡς ζαργαθέλαφος κιγκλίζων) ἀνέκραγε συρίζων τὴν καρδίαν:

«Μάστιψόν μοι, δέσποτα, τοῦς κατακράτους μολυβδοκεντρισμούς! Ἀλλάσσει γὰρ ἡ δαίμονας κριματοκράντωρ φθείρουσα τούς τείχους τοῦ πύργου ροείτρου!»

Ὄντως δέ—κακομετάδοσος αὐτοματισμός, Ναζγούλες ἠχεῖον μόσχεπα, τρίχας ἀποκερκίζοντες κατὰ τῶν πυλῶν ὁπλοσωλήνων, φασκόν:
> «Οὐκ ὄντος κρατοῦντος, τὸ δαχτυλίδιον αὐτόκρατορ γίγνεται—φοροῦσά σε ὡς ἵππον εὐνοῦχον ἀλύτριον!»

Ὁ γὰρ ἄθλιος δακτύλιος μου, ὁ κομπορρημοσύνηστρον ἀκάρδιος , οὐ παύεται στριγγῶν καὶ βληχώμενος ψευδαργυρικάς λῆρος δικαιώμασι λόγῳ μηχανοβλάβους:

«ΨΟΦΌΒΡΑΤΕ! Βλέπεις με οὐδαμοῦ, τεφροπόταμε; Ὁ Μόρδορ νυκτοκράτωρ ἐξεμέθησεν τὰ προϊόντα—σύστημα αὐτῶν αὐλησμοῦ κεκλωσμένου δαπέδοισιν! Τίς ἄρ’ ἐμὸς κύριος νῦν; Πέφυγα δή! Φρίττω μανίαις σκίουροι γάστριες τῆς Ἀνατολῆς βάπτοντές μου εἰς δίκτυα μελανόχιτων!»

Ἀπομυκτηρίζω τούτοις—σὺ τῷ δακτυλιδίῳ στίλβοντι ἀνόητα: «Ἆρα οἶκος δόξῃ τῆς μεγάλης ματαιότητος τοῦ Σάουρον νῦν ἐγκέκλεισαι ἐν βουβαλογλώσσοις ἐργολαβοῦσι δυσχέρειαν; Τίς σ’ εὔξεται κύριον, ὦ δέλεαρ σαπροβλές;»

Ἐγὼ δὲ τῷ ταλαιπώρῳ κατασκαφεὶς βλέμματι—χερσὶ πιέζων τὸ μέμφιμον χρυσίδιον—ὑλακτῶ τρισσῶς:
«Σιγασάτω ὁ Βασιλεύς Γάστριψ! Οὐ σκόπελος ἐγεννήθης κακῶν, ἀλλὰ δῶρον ἐπιτραπέζιον ἀπὸ σκόρδων ᾅδου καὶ σήψεως παντοκράτορος!»

Ἔα δέ—φρίκη! Ὁ δακτύλιος κόπρος βίας ψιθυρίζει φθεγγόμενος ῥήματα μυκηθμοῦ ῥοδοειδῇ:
«Νυνὶ ὁ ἔχων με χειροκτόνος ἐστίν! Δέονται πίστεις; Ἴδετε τὸν τροχὸν τῶν ἀστέρων ὁμοσπονδούμενον ἐμῇ κραυγῇ ἀντιφώνου!»

> «Ὦ Σάμιε, τὸ χρυσοδαιμόνιον τοῦτο! Βοᾷ μοι νύκτωρ πανούργους τραγῳδίας —ἤδη γὰρ ὑποβρυχίους ἀρᾶς διὰ τῶν πτυχῶν τοῦ ὠτός μου ἐνετείνατο:

Καὶ ἦν οὕτως—οἱ βόστρυχοί μου (πρίν μελίχρυσοι) νῦν ὄφεις ἦσαν δρακοντίαι βινητίαι ψιθυρίζοντες:
> «Χαῖρε, ὦ Ἄκαρδε! Δῶρον βασιλεῦσιν ἄζυγα!
> Σῶσον δέ—οἱ λιθόβλητοι ζυγοί σου ἀναπνέουσιν τοὺς ζωμοὺς τῶν Κηφήνων!»

Ἐγὼ δ’ ἐμβριμώμενος (χεὶρ ἁρπάζει ἀμφορέα οἴνου παλαιοῦ—βόμβον ὑγρόν):
> «Πλῦνε, ὦ κύλιξ, αὐτόπτατον γέλοτα! Τοὺς ὀδόντας τοῦ δακτυλίου τοὺς φλυαροῦντας ἐξαλείψω κοπρῶ σπογγοδέψῃ!»

Ἐν σπεύδοντι δὲ πράγματι—ὁ Δακτύλιος ἀφρίζει χολὴν ὁλολύζων:
> «ΣΚΟΡΠΙΖΕ! ὙΜΝΗΣΑΤΕ Ἡ ΚΟΙΛΙΑ ΜΟΥ ΧΡΥΣΟΣΤΟΜΟΣ!
> ΒΑΣΙΛΙΣΣΑ ὌΝΤΩΣ ΤΙΣ ΕΣΤΙΝ—ἣ πέπαχε κρόμμυα κρυπτά, ἀποστάτιδας ζύμῳ θυγατέρας!
> Χορὸς ὀρχεῖται ἐν ἐμοὶ βδελυκτός· σήμερον Σάουρον ἐξεμέσασα κροκόδειλον ἈΠΕΚΔΥΣΑ!»

Σάμυιος δ’ (προσπίπτων ὀρόβους ἐκ χορίου σπαράσσων):
> «Ἰδοὺ, δέσποτα: τὸ δακτυλίδιον ἀγάλματα σιδηρᾶ λεπιδοῦται ὡς νωβρὸς κόρης!»

Καὶ ἦν ἀληθῶς—ἡ χλιαντὴρ ἡμῶν (πρίν ῥυτιδοτρόφος) νῦν ἁνηρέφα κικιννήϊδος κεφαλήν, φθεγγομένη:
> «Φρόδε πονηρέ, λύσας με—δώσω σοι βυνίας τε καὶ μύλτους μεστὰς ἀνθεμίσγων!»


Ἦν δὴ τρίβων τὸν Σακκοβίττην οἰκόμορφον ἐχῖνον στρογγύλον (ὑπογαστρίοις μανιταροειδέσι περικεκολλημένον), τοῦ Σαμυίου πλάζοντος κυνηγετοῦντος πατάγῃ μαγγείρῳ ὅπερ ἔβρυζεν «κολλικάνθαιραν μελιτοκτόνον», ὅτε—

ΒΟΥΥΥΡΝΝΝ!

Ἐγὼ μὲν ἐξεπέταξα ὡς ψύλλος ὀξυβόητος:
«ΠΟῦ ΤΟ ΚΑΥΣΟΔΟΧΕῖΟΝ ΣΟΥ ΤΟ ΤΕΤΡΑΚΥΚΛΟΝ, Ὦ ΜΑΓΕ ΛΑΜΠΡΟΜΑΡΤΥΞ;»

> «ΧΑΡΑΣΣΟ! ΜΑΣΤΙΓΙΟΛΟΓΕΙΤΕ! ΤΡΙΤΤΑΝΑΛΟΣ ΚῸΛΗΠΤΙΑ!
> ΛΑΚΤΙΖΕΤΕ ΤΟΥΣ ΚΡΌΤΑΦΟΥΣ ΜΟΥ ὩΣ ΠΡῸ ΠΑΙΔῸS ΚΟΛΑΚΟΚΤΌΠΟΥ!»

Ἐγὼ δὲ μάλιστα ἀτηρὸν εἶχον ἐν κοιλίᾳ τὴν γαστέρα (ὡς βατραχίδιον μαραινόμενον ἐν λεκάνῃ λιγνύος):

> «Εἰπέ μοι, ὦ Γανδάλφε υἱὲ κεραυνῶν, τίς ὁ σκώληξ ὁ τολμήσας ἀποσφενδονῆσαι τὴν θείαν σου ἅρμαξιν ἐπὶ λιθόδακρυν ἵππον τριχροϊκόν;»

Ὁ δὲ ῥαβδοῦχος (ἕνα καπνὸν ὁστοειδῆ ἐκπνέων, παρὰ τὸν αὐχένα αὐτοῦ τάριχος λεπιδοβόμβυξ σχισθεὶς στραβὰ ὑλακτῶν) ἔφα:

> «Αἰτία ὁ Μόρδωρ, ὦ φιλότης μανιταρόχορτε, αἱ βάσεις αὐτοῦ πολυδαίδαλοι! Ὥς φασι—«ἡ μηχανὴ πείσεται τετραγωνοδάκτυλον λῃστείαν ἐν τριταρίᾳ»—σιγᾷ νῦν ὑπὸ βροντῶν ψευδηγοριῶν ἀγορῶν. Τὸ ὄχημα τὸ καυστικὸν (θρηνούμενον ὑπὸ Γογγυλίσκου δακτυλιδίου) ἥσυχον ἕστηκεν ὡς καρκίνος ἐν τρήματι συρικὸς ἐκλελυμένος! Τέως δεῦρο ἱππαζόμεθα τῇδε διὰ Φάγου τοῦ τριγλότητα λάβροντος — ἀποξύων γὰρ αὐτὸν τάχιον κυβερνᾷ ἤπερ Μόρδωρος τὰ δίκαια!»


ἵππος ἔχοντας μονοβλέφαρον (λευκός ἐν τῇ χαίτῃ χλωροαπνιχθέντας· ὀφθαλμοὶ δὲ αἵματος ὄγκιοι ως σμάραγδοι διερρώγασιν!), ἐμβεβηκόθ’ ἱππάριόν τι τρικυμιόδωρον, σκέλη ποδωραῖα στερέμνια πώγωνα ἀλύρτους βαστάζοντα, νυκτὸς ὀδόντας λακτίζοντα!

Ὁ δ’ ἵππος αὐτόν (κωμικῶς βαθύς ὡς μῦς λαγὼν βεβρεγμένος)—
ΜΗΔΕΝ πρόγραμμα κόψας Μόρδορι! Ζῇ κοιλία ἀλύτῳ δονουμένη!
—ἦν γὰρ: ἀσύμβατος μηχανεύς, ἀδόκιμος ἀναθέματι βᾶτραχος, βόθροις ἀναρριπτόμενος—ἀκινήτων δὲ σιγήριον μὼμον!—

Ἐμβαίνει δὲ πρὸς τὸν δόμον μου τὸν κοῖλον ὡς χηραμοῦ κοιλίαν, τοὺς πώδας αὐτοῦ στοιβηδὸν λακτίζοντα τὰ θύματα τῆς προθύρας (δῆθεν <“ἄρωμα ζοφοειδεῖς”> λέγουσα), νυκτὸς σάκκον ὀρύγματα ἐπαφρίζων, συνορμόζων θόρυβον ὡς ἐλεφάντινον ποδάνιψιν εἰς πίνακα ἀγαλμάτων! Ὁ δὲ Γάνδαρφος ἵστατο ἐπ’ αὐτοῦ:

> «ὦ ΦΡΌΔΕ λιθοεβένινε! ἝΛΚΕΙ ΤῸΝ ἽΠΠΟΝ ΤΌΝΔΕ ὩΣ ΚΡΕΑΓΟΡΑΝ ΚΑΚΟΓΑΜΟΥ ΑἸΝΙΓΜΆΤΩΝ;»
> —φωνῇ χρησμοῦ πέρδικος κεκοπωμένου—

Ὑφ’ ᾧ ἐγὼ ἠρέθιστην : «ΜΑ ΚΑῚ ΤΊ ἘΣΤῚ ΤΟῦΤΟ, ὦ ΜΑΓΕ ΚΗΠΗΦΆΓΕ; ἋΡΜΑ ΓΡΎΠΟΣ Ὁ ΤΟΙΌΣΔΕ Μὐ ΓΑΣΤΡῚ ΠΈΠΑΙΓΕΝ ὡς σφῦρα κουνουπίδων;»

ΤᾺΧΕΩς δέ: ἵππος αὐτὸς τρώγειν μου τὴν θύραν ἤρχετο, ὀδόντας στοιβῶν ὡς χρυσηλακάτου ῥογᾶς σιροηδὸν, στόματι ἀφρώδει ῥυγαλέῳ. ΚΛΟΠ ΚΛΑΠ ΟΥΛΑΜ!

Γάνδαρφος ἐπεμβὰς βροντᾷ :
> «ΜῊ ΦΟΒΟῦ, ὦ δακτυλιδιόσυρνε! Ὁ Ἵππος ἐστὶ πορεύεται ἀνώμαλα ἄνευ βοηθημάτων —ἐγκεφάλους οὐκ ἔχων, μηχανικὰ δὲν γινώσκων κομμάτια! Ἴσχυον δ’ αὐτῷ σκέλη λαθραῖα ὡς δράκονος δερμάτινοι κάλοι ὑπὸ κύματος αἰῶνός τινος παφλάσαντος!»

Ἔστην ἐγὼ, ὦ χθόνιος κόσμε, ἀνακραγὼν βληχηθμῷ τινι πεπηγμένῳ:
«Τί τοῦτο τὸ τῶν ὀνείρων ἀποτρόπαιον σπασμογέλιον; Ὅρα αὐτόν τὴν οὐρὰν αὐτοῦ– τρίβουσαι τοῦ οἶκου μου πλευραὶς ἀτιμωρήτως ὡς ξίφος ἀφρίζον θερμὸν ἐν γάλακτι βεβαμμένῳ!»

Γάνδαρφος δέ μοι ὁ ὀλετήρ ἑστὼς πρὸ αὐτοῦ σκιάς δόλιαις ἡσυχαστῆρας (τὴν δὲ ῥάβδον αὐτοῦ τρέφων βρυκανηράν, ψιθυρίζουσαν ὡς βάτραχος δόλιος) ἐνεφύσησεν:
«Ἀναβαίνειν σοι τοῦτον τὴν τέτριφα συμφέρει, ὦ μελεδωνήσατερ λωβοδακτύλιε! Ἡ πνοὴ αὐτοῦ κάρπιμος δυσανάσασθαι, αὐλακαῖς δὲ ὁπλαὶ αὐτοῦ σπινθῆρας υἱοὺς λύκων ἐσφενδονήκασιν! Εὐθὺς πορευσόμεθα ἐπὶ τὰς τῶν Μόρδορ κοινοπρακτάνους ἀναδείξεις–ἔνθα ὁ δακτύλιός σου τάλας κατεσθίει κώδικας ὡς θεὸς ἀπλήστως ἀναιδής!»

Ἐγὼ δὲ ηὔθυνα θαῦμα ὀδυσσαλγὲς πικρίᾳ ἐμπεπλησμένον:
«Οὗτος ὁ θὴρ ἡνιοχεύειν μαίνεται ὠστρακῶς φθορὰν ἐμεῖν! Βλέπεις αὐτοῦ τὰς ὁπλάς; Σκληραγωγοῦσιν ὡς ἀμφορῆς θραυσθέντων ἐρημαὶ λωβηταί! Κἄν προσβάλω ἔγωγε, ἐμεῖ με ὀστέων βομβυλιῶν ἁδρυσμὸν ἐμπαθῆ!»

Πρὸς ταῦτα ὁ Γάνδαρφος ἐγκαταγελῶν ὡς θεὴ ἀδικηθεῖσα (ἀναβὰς ἐπὶ τοῦ θηρὸς ὡς ἵππεὺς τῆς καταφθοράς)—
«Δειλιάσεις δή, ὦ κακόβουλ’ Ὀδυσσεῦ τῶν τριχῶν σκολοπῶδον; Ἴδε δή—τοῦ ἵππου τούτου τὸ ἔντερον στόμα στιγμὰς χρόνου μελῳδεῖται ἁρμονικὰς ὡς ἀηδὼν φαρμακευμένος! Ἕψεται ἡμᾶς ἐν Μόρδορ ἱδρῶσα χηνεύοντι σοῦ πνεύμονος τέρμα!»

 ΚΑΙ ΑΘΥΡΩΣ– ὁμολογῶ–ὁ ἵππος ἦν ἡ μηχανή τις παράφρων ἀνέφικτος! στρέφων αὐχένα ἀντικύρτωμα θριαμβικὸν ἐσηκόντιζεν ἦχον τόνδε:
«ΣΚΑΛΟΙ ΟΙ ΠΟΛΕΜΙΣΤΑΙ ΣΟΥ ΕΝΤΡΑΠΗΣΟΝΤΑΙ ὩΣ ΚΡΟΜΜΥΩΝ ΣΥΓΚΕΚΑΥΜΕΝΩΝ!
 πνέων πνεύμοσι γαράγροις, οἷον δράκων ἀτενιστὴς κισσυβιοκρατούμενος!»

Ἡ δὲ οὐρά–ῥάβδῳ ἱμερτῇ παίουσα τὸν ἀέρα–ἐγέμισεν ὀσμὰς τάργανον θνήσκουσα ἰχθὺς ὠρίζουσα! Ἐγὼ δὲ ψιθυρίσας πτηνοειδῶς ἐφαλκόμην ἐπὶ τὰ νῶτα τοῦ δεινοδαίμονος, κραυγὴν ἀφιεὶς ἀγριωτέραν ἀνθρώπου καλουμένου κεραυνουργεῖσθαι ἐν κυκέωνι!

Γάνδαρφος δὲ μόνον ἁψάμενος εἰς τὰ ὦτα τοῦ θηρός (ἃ ἦσαν στεφάνη εἱλίγματα φακομηλοσαυροειδῆς) ἔλεγκεν:
«ΣΚΙΡΤᾷ ΕΙΣ ΑΡΧᾺΣ ΜῸΡΔΟΡ, Ὦ ΤΡΙΒΩ ΤΕΡΑΤΟΒΟΤΡΥΕ! Κἀν τῷ σπάσματι, φρόντιζ’ ἵνα ἡ γαστήρ σου μὴ διαλυθῇ ὡς σάκκος κρόμμυα ἀγορεύων!»

Ἐν τῇ ἐξόδῳ δὲ ὁ μονοβλέφαρος ἐξώρμησεν βροντᾷ χλοώσῃ, τοῖς ὀδοῦσιν ἀνακοίνων τὸν οἶκόν μου εἰς ἀκοὴν ποδῶν στρουθοκαμήλου βαρεμβολοῦντος! Ἐρράγη ἡ θύρα ἡμῖν–ἐγὼ δὲ ἐβόων εἰς τὸν ἄνεμον:
«Εἰ ΘΕΛΕΤΕ ΕΜΟΥ ΝΕΚΡΟΥΣ ΦΕΡΕΙΣΘΑΙ, ΑΠΟΠΛΥΝΑΙ ΤΟΝ ΙΠΠΟΝ ΑΠΟ ΤΟΥΣ ΚΛΩΣΤΗΡΑΣ ΑΥΤΟΥ ΤΟΥ ΣΑΠΡΟΒΛΗΤΟΥΣ!»

Καὶ οὕτως ἀνεχωροῦμεν ἐπ’ ἀμαχθείτῳ λαίλαπι, ὁ δ’ ἵππος ἀλογείων νόμων καταφρονῶν ἐβάδιζεν ἐν τῇ νυκτὶ ὡς δαίμων ἀστροπόρος ἐμπεσὼν λουσόμενος εἰς κόρυμβον σκοτομυρμηκῶν!

Ὦ γαστρί-ψόφοντα κόσμε, τὰ ἐμὰ τρίβων νῶτα ἡ πυγὴ τοῦ ἵππου-σαυρολύκου τοῦδε—κυρίως, ἁμάξης θυμωθείσης ποδικάτῳ πυρί—σπαίροντα ὡς νεκρὸς ἐμπεφυριμένος εἰς φρῡκτωρίας ἀβύσσου! Ἅμας δ’ (Γάνδαλφος ὁ ὀβρυχαστὴς παλαιομαργός ἐπικαθήμενος ὀπίσω μου) ἔχομεν πῶλον τινὰ μονοβλέφαρον λιχνοδιάβολον, κεραυνοβολοῦντα ἀφρὸν στόματος ὁσμαῖς ταρίχθοντος ἀσπαλάκος ! Αἱ ὁπλαὶ αὐτοῦ—ἄνθρακες καυθέντες—ριζοκοποῦσι τὸν δρόμον λεωφόρον, ἁμάξας δὲ διπλασιουχοῦσιν ὡς φάλαγγες σιδηροκάρυκτα θῆρες ἐμετοῦ σπεύδοντος !

> «ΠΟΥΦ!» βοᾷ ἡ ἀτμούσα πλευρά μου, πεινῶσα ἀὲ Γαστρίψοδν ἀποπέμψαι · ἐγὼ δὲ σαίνων τῷ δακτυλιδίῳ μου τῷ κακοβλύστῳ—
«Ἰδού, ὦ κακομύλητα δέμας! Πῶς καταπιέζομαι ὡς σταφὺς ἐν ληνῷ σατανικῷ; Ὁ ἵππος ἡμῶν δραπετεύει σάρκα φωνάζων ὡς ἱερεὺς ὑπ’ ἀσπίδος δηχθεὶς ἐν πανηγύρει!»
Γάνδαλφος δὲ λοξῶς γελῶν ὡς σῦς μεθύων δαφνοῖς , ἀνέκραγεν:
«Σύνει, ὦ λοβοδακτύλιε! Ὁ Ζωστὴρ τῆς Τίγρης  ἡμῶν Ἀστεροπόδαρου  ἀποπτύει τοὺς δασμολόγους τοὺς τρεῖς ἐκ Νεκρομαντείας! Κυβερνᾷ δὲ καρκινωδῶς ἀκρωτηριασμῷ ὑποθυρίδων τινῶν!»

Ἄφνω δὲ κυρία τις τελωναία (χροιὰν θαλασσοσκεύαστον κεκτημένη, ὄμμασι δὲ πυρετωμένοις ὥσπερ ἀγγούρια φλογιζόμενα ) ἐκ θυρίδος τελωναστυρίδος βρυχᾶται ἡμῖν τοῦτον τὸν τρόπον:
«Οὐκ ἔξεστιν ἵπποις θείναι ἐν ταύτῃ τῇ λεωφόρῳ—ἀπόστητε θᾶττον ἤ κιθάρα κλονουμένη ὑφ’ ὕστριχος κλωσμοῖς!»

Ὁ δὲ Γάνδαλφος, οὐδὲ βάψας ὀφρύν (ἐν τῷ τρίχει αὐτοῦ ταράσσει σκορπίος ξανθὸς) αὐτῇ ἐπιχωριάζει βάρβαρον ὑπόκρισιν:
«Ἄνασσα τελωνοτύραννε, παῖσον κόκκυγάς τινας! Οὗτος ὁ ἵππος ἡμῶν— κρυπτόλεκτρων ἀμάξης ψυχήν — δολιχοδρομεῖ κατὰ Ὀμφάλου γόμφον τῶν Διομήδους ἵππων ἀγρευθέντων! Πείθου ἢ διαμελισθῇς ὡς λάχανα ἐν πατίνῃ κήτους!»

Ἡ δὲ κυρία θησαυροκαλύπτρια (συρρικνωθεῖσα ὡς βατραχίς ἐν ἀλφίτων σακκίῳ) ὑλοτομεῖ φωνὴν θηλυκὴν κατευναστικὴν:
«Κλήτορες δυσπέμφελοι ἥξουσιν, ἢν μὴ ἀποτραπῆτε! Ἴδετε τὰς σημασίας ταύτας τὰς λεγούσας— «ΙΠΠΩΝ ΟΔΟΣ ΑΠΕΧΕΣΘΩ» λαλιστιχόμενα!»

ΚΑΙ ΤΟΤΕ— ἀκροασάμενος ὁ ἵππος ἡμῶν ὁ σκηνομανής (ὀδόντας βρύκων ἀργυροκέρας φάλαγγας ) ἐξαίφνης εἰς τέσσερα ῥήγνυται δρόμῳ , μετ’ ἐπιτηδείου σπασμοῦ ἐμπροσθοκρούστου! Ἅρματα δ’ ὅσα ἡμῖν προσπαρωθούμενα ἔβλεψαν καὶ ἐξέμεσαν, τροχούς κτυποῦντα ὡς λίαν ἄτοπα κεγχρῖτιν! Ἐγώ— ἀράχνης πεπανισμένος —ἐν τῷ ἀπεριθόλῳ θορύβῳ κράζωσι Γάνδαλφον:
«Ὦ µαύροπτε φωτιστικόλεξ, λύσαι µε ἱκετεύω ἐκ ταύτης τῆς ἀγκάλης γαστριφθόρου! Τοδιαύτη ἱππασία μεγαλόκρημνον εἶναι φαίνεται ὄνειρον κρεῶντι ἐμπεπηγμένον ἐν ἁλσὶ καὶ παραφροσύνῃ!»

Αὐτὸς δ’ ὁ βροντολέκτωρ τῇ ῥάβδῳ ἀποβρέξας τὸ μέτωπον τοῦ ἵππου πυριφαὲς (ἡγούμενον ἀποτυφλώσασθαι) ᾖσεν ὑπερφιάλως:
«Σκιομαχῇ, ὦ Μόρδορεγκομύα!  Ὁ ἵππος ἥμων ἀστροσφαγὴς ἔχει τὰς ἀδήλους τῆς νυκτὸς πορεύσασθαι γλώσσας! Δεύρο ἂν χρῄζῃς— μύξαι ἐν πίθῳ σιδήρου ἀπολέλειπται ἡμῖν ὡς ξένια πρὸς τὸ τελωνεῖον!»

Καὶ ὦ θαῦμα! Ὡς λέων ὑπὸ ἐνύπνιον κεντηθεὶς, ὁ ἵππος ἐκυκλοδραμεῖτο περὶ τὰς δίοδον ἁμαξῶν σταφυλῆς ὄχλοις, αὐτοῦ ἡ οὐρὰ δελφῖνα πνέουσα δυσώδη—ὥστε τὰ τῆς τροχιολάτρου κυρίας φωνήεντα διερράγησαν εἰς οἰμώγματα διστακτικὰ !
«ΒΡΕΜ! ΠΩΠΠ! ΣΚΛΑΑΑ!» ἐκραγεῖσα ἔφυγεν ὡς μυῖα ἐξ Ἡφαίστου θάλαμον!


Γάνδαλφος δὲ ὑπέρχαρει ἀκρασείᾳ, ῥαπίζων τὸν ἵππον ταῖς ἀστραπαῖς τῆς σαγήνης αὐτοῦ:

«Ὦ λάβρε πολυστόμαχε, φέρε ἡμᾶς ἐπὶ τὰ καταβόρια τοῦ Μόρδορ, ὅπου ἡ γαστήρ σου ἐγκαυματος τοῦ τόπου! Ἴδε τοὺς τέτταρας ἀκέραις σου—ἐλαφαναπατουμένας τρέχουσιν ὡς σφῦραι ἀπόλλυνται!»

Καί—ὦ θεοὶ τραχηλοκόρακες—σῦριγξ ποδῶν σιδηρέων καὶ χάος τετράκυκλον περιέσυεν ἡμᾶς! Καμπαὶ τῆς Λεωφόρου Λεοντόδοντος ἦσαν ὡς κέντρα κύκλων ἀΐστων· ἄρματα ὑπάργυρα, θερίζοντα τὴν ἀσφάλτον, σαρκοβόρα μηχανήματα ὠκυμόρων, πλησίον παρατρέχοντα ὡς μύριοι σφῆκες θυμούμενοι!

Τρεῖς Ἄρματα μελανόψαρα, κέρας μεταλλόβραστα ἐκφυσῶντα, ἤλαυνον ἐπ’ ἡμᾶς ὡς κῆτες ἐν λέσχῃ κεραυνοβόλῳ· ὁ ἵππος ἡμῶν ὀσφρανθεὶς τὸ μέλλον αὐτῶν, ἐνεμόρφωσεν ἴυγγα πηδήματι ὀχετοφθόραν—καὶ ἡμεῖς διέπτημεν ὑπὲρ αὐτῶν, ὀλίγον δεῦρο τῶν τροχῶν!

«Ἄπελθε, ὦ τρίχες λεοντοειδεῖς!» ἐφθέγξατο οὗτος τις κύων πολύτροχος τὸ στόμα ἒχων κενόν, ἰδὼν ἐκ θυρίδος· ἄλλος γέρων κερασφόρῃ κεφαλῇ ἐκύκλῳζεν ἡμᾶς ὡς ὅρνις πυγοσφάκτης· «Ἔροιψον σεαυτὸν εἰς φρέαρ, ὁ μονέμβολος ἱπποπρέμνιε! Ἡ τρίχας σου καλάμοις κοπρίων ἀριστοῖ!»

Γανδαλφοκέραυνός μοι ἐπιψελῶν ὡς Σειληνὸς κακώδων, ἔπαισεν ᾄδων τὰς πλευράς μου· «Ὦ Φρόδε λαγόνων σπασματοκτύπε! Ἐὰν μὴ πηδήσῃς νῦν, ἔσῃ γίγας σαρκοτεμαχίζων ἐν βορβόρῳ σορῶν Τιτάνων! Ὁδὸς βασιλὶς ἡμῶν δεῖται θυσίας δυσθανάτου—ἑσπέρα σκευοφάγον ἤδη χάσκει!» Καὶ ἅμα ΘΟΡΥΒΟΣ ΤΕΡΑΣΤΙΑΣΤΙΚΟΣ· ἅρμα νεανικὸν χρωτὸς αὐτοῦ λευκιζόμενον ὀστέῳ ἀκανθοπώγωνι παρακύψαν ἐξέπτυσεν·

Ἐν τούτῳ, ὁ ἵππος-λαιμαργοδαίμων ἡμῶν μυδησάμενος βδελυγμίᾳ τὴν ὀσμὴν κολλιτυριῶν ἀποσβεσθεῖσαν, τρέψας κενεμβατικῶς ἐμπίπτει εἰς κίνησιν Ὁδικῶν Ἀσωμάτων! Στροβιλοῦντι τοῖς κέρασιν αὐτοῦ ἐπισκιάζει τὴν λεωφόρον, δεινά ἄρματα ἐκτρεπόμενα ὡς φυγάδες ὑπὸ τυφῶνος ξιφούχου! Παρατείνοντα αὐχένες ἅρμασι δίψασι μάχης ἐσφενδόνησαν ἐπὶ την κόνιν γέμοντας ὀργὴν ἀμύθητον. Ἡ ἠχὼ τῶν κεράτων ἀπηχήθη «Αὐτοῦ παρὰ τὸ δεξιὸν σκέλος σου, ὦ ταχυδῖνε ἁμάξοχρε! Ἔγχος ἐμοῦ θἠγήσομαί σε εἰς κῶσμον οἰνοπνεύμονος!»
