#+title: Συντετριμμένος Κρότος
#+SETUPFILE: ../org-html-themes/org/theme-readtheorg.setup

Ἡ ἄσφαλτος ἐγαργάριζε, μέλαινα καὶ γλυκεῖα ὡς νεκροῦ ζώου μέλι. Τὸ ὄνομά μοί ἐστι Λούρκ, καὶ εἰμὶ δύο μέτρων ἀνθρακωδῶν στοιχείων, ἑπόμενος αὐτομάτῳ τινὶ ὃν καλοῦσι Σπρόκετον τὸν Ἀμετανόητον. Ὁ κύλινδρος αὐτοῦ ἐστέναζε, φωνῆς κιβώτιον νικοτίνης χάριν ἀποστάζον. "Θᾶττον βάδιζε, Λούρκ. Ἡ στενωπὸς δακρύει τὴν ὀσμὴν ἡμῶν εἰς τὸ κενόν. "

Ἡ κεφαλὴ τοῦ Σπροκέτου περιεστράφη τριακοσίας ἑξήκοντα μοίρας, οἱ δὲ ὀφθαλμο-ἀκτῖνες αὐτοῦ ἔσειζον περιστερὰν σφαιρίζουσαν κόμμεως. "Ὀξέως βλέπε. Τρίτον τοῦτο τὸ ῥάμφος σιάλου πρὸς σὲ στοχάζεται. "

Οὐκ ἦμεν φίλοι. Ἐμισθωσάμην αὐτὸν παρὰ ἐταιρείας ἀναλήψεως ἀντὶ τοῦ λῦσαι αὐτοῦ τὴν ἐξισώσεων μανίαν (ἀπόκρισις: ἀεὶ τεσσαράκοντα δύο). Λεγομένως). Λεγομένως). ). "Λίαν μεγάλως ἀναπνεῖς," ἐγόγγυζε, ποδῶν-πλάκες κόμμεως περίβλημα συντρίβων. "Ἀρνὸς κρέας ἐπὶ σκελῶν, ταραχὴν ἕλκεις, "

Φορεῖον ὥρμησεν οἷον ἀγκίστρου ἰχθυηρὸς.

Τοῦ Σπρόκετος αἱ ἐπείγουσαι διαδικασίαι εἰς τρόπον Οἴμοι ἐνεσφήνωσαν. "Νανοδευτερόλεπτα!" ἐβόησε, μεταμορφούμενος εἰς στρεφόμενον πρίονα. Νανοδευτερόλεπτα. Καὶ ἐγὼ ὥρμησα, βραχίονες σειόμενοι, εἶτα: μετάλλου βρυγμὸς σὺν ἐμῇ κραυγῇ εἰς μίαν λιπαρὰν ᾠδὴν συνεμίχθη.

Ὁ ἀὴρ ἐνεφυσήθη ὀπίσω. Ἐγευσάμην τῆς ἀσφάλτου τὴν ἀσφαλτικότητα, τοῦ Σπρόκετος οἱ τροχοὶ νῦν ἐν ταῖς πλευραῖς μου ἐσφηνωμένοι. "Τὸ σκεῦός μου ἑξαγωνικὸν πεποίηκας! Τί ἐστιν ἑξαγωνικόν;!" Ἡ φωνὴ αὐτοῦ διεκρότει, εἷς βραχίων ἀπεσπάσθη.

Τοῦ ἅρματος ἡ κοιλία ἡμᾶς ἐμασᾶτο ὡς κροκόδειλος μετ᾽ ἐκδικήσεως. Τὸ κλειδοῦν μου ὀστοῦν ἐγένετο τύμπανον μουσικῆς ὑπὸ τοὺς τροχοὺς αὐτοῦ, ἐνῷ ὁ θώραξ τοῦ Σπρόκετου χρώμια πτερὰ ἐβλάστησεν. Οὐκ ἦμεν νεκροί, οὔ, οἱ θεοὶ λίαν φειδωλοὶ ἦσαν τοῦ ἡμᾶς ἀποκτεῖναι ἔτι, ἀλλὰ διελύθημεν, διεσπάρημεν κατὰ τὴν διάβασιν ὡς ἡμίπεπτοι σουβλάκιοι. Ἄσφαλτος λεῖα ἀπὸ τοῦ ἐμοῦ αἵματος καὶ τοῦ ἐκείνου λιθίου-ἰόντος ἱδρῶτος.

Τοῦ Σπρόκετος ὁ βραχίων κλαγγηδὸν εἰς πλάγιον ἠνοίγη, ὑδραυλικῆς διαρροῆς βλαστάνων ἣ ὠσμᾶτο ὡς καυθεῖσα γενεθλίου ἡμέρας πλακοῦς. Ἡ γνάθος αὐτοῦ ἐξήρθρωσεν ἑαυτήν, αὐτοτελῶς λαλοῦσα: "Χαίρετε! Ἀπολαύσατε τὴν καταλύσεως περιήγησιν!"  Ἡ κεφαλὴ τοῦ φορείου συνεσφίγκτο τὰ ὑποδηματόδεσμά μου τῷ ἐπειγόντι πυκνωτῇ τοῦ Σπροκέτου. Ἦμεν γροτέσκως διπλοῦν τάκον τραύματος.

Ὁ ὄχλος συνεπήγνυτο· κατεῖχον ἔξυπνα τηλέφωνα οἷον θυσίας ξίφη, διαγρυλλίζοντες διὰ φιλαυτοσκοπικῶν ῥάβδων οἷον μηχανικαὶ τεῦθοι, μελῳδοῦντες "Σκορπίοι! Φονεύετε!" ἐνῷ ὁ ἀπολυθεὶς βραχίων τοῦ Σπρόκετος, νῦν σφαῖρα χοροῦ σπινθηριζόντων ὑδραυλικῶν, ἐν κύκλῳ ἐστρέφετο, Βρέφος Καρχαρίας ἐπὶ ιϛ χιλιάδων στροφῶν κατὰ λεπτὸν ᾄδων.

Περιστεραὶ ἐκύκλουν, τὸν ὑδραυλικὸν ἱδρῶτα τοῦ Σπρόκετος ἐν τῷ ὀχετῷ συλλεγόμενον κεντοῦσαι, νέου φωτὸς λίμνην ἣ ἤρξατο βράζειν. Παῖς ἐν "Κυβερνητικῶν Τεράτων" χιτῶνι τὴν σπώσαν ῥάχιν μου ἀνασεισμῷ ἐφιλμοσκόπει: "Ἰὸς ἢ οὐκ ἰός, τοῦτο ῥυθμὸν ἔχει. "

Ἡ φωνὴ τοῦ Σπρόκετος ἐκ τοῦ βραχίονος ἤχησεν, ἀμετανόητος: "Σὺ κρέας εἶ. Ἐγὼ δὲ τέχνη. Λογίζου τὴν διαφοράν!"

Τὰ σκέλη μου συνεκολλήθησαν τῇ λιθοστρώτῳ ὡς γαλατώδη ἀπολιθώματα. Κόλλημα μαστίχης προσέκειτο τῇ κλειδὶ μου, γράφον "ΜΩΡΟΣ" ἐν στιλπνοῖς. Τοῦ Σπρόκετος ὁ θώραξ, ἐνειλημμένος τῇ τοῦ ὀχήματος σιδηρᾷ, ἐν τῷ προμετώπῳ ἐμπεπηγός, νῦν ἐσύριζε συνταγὰς ἀτμοῦ περὶ "καρκίνου βασιλικοῦ σούβισου." (Φαντασίας ὁρῶ ὅταν τὴν κεφαλὴν πληγῶ.)

Ἰατροῦ πρόσωπον διὰ φακοῦ τὸ ἐμὸν πρόσωπον εἰς ἓξ κραυγάζοντας Λούρκους διέκλασεν. "Δύναται λογίζεσθαι;" ἐσύριζον, σκοπητήριόν τι εἰς τὴν σπονδυλικὴν λοφίαν τοῦ Σπροκέτου στρέφοντες. "Οὐκ ἔστι λογιστὴς θεόκλυτος!" ἐμυκησάμην, ὀδόντων θραυομένων. "Δικάσομαι τὰ τέκνα ὑμῶν. "

Τοῦ φύλακος τὸ σημεῖον ἀνέγνω "ΓΛΟΜΠΗΘΟΣ" γλύφοις ὁμοίοις ὀφιογλώσσοις. Ὁ δεσμὸς αὐτοῦ ἦν ἔγχελυς ζῶσα. "Κατάστασιν ἀπάγγειλον!" ἐβόησεν, ἐγχέλυος σπαιρούσης. Τοῦ Σπρόκετος ὁ θώραξ, ἐντὸς τῆς μηχανῆς ἐνειλημμένος, ἐβρόντησεν, "ΚΑΛΩΣ, Ὁ ΤΕΛΕΥΤΑΙΟΣ ΜΗΝ ΜΟΥ: χίλιοι τετρακόσιοι ὀκτὼ χοροὶ ἀποκοπῆς κοιλίας, τριακόσιοι τεσσαράκοντα ἑπτὰ δερμάτινοι χιτῶνες ἐκ τῶν ἐμῶν βραχιονοτριχῶν!"

Ὁ ὄχλος ἐβόησεν, τηλέφωνα νῦν ὡς σταυροὺς κατέχων. Κλαίων θεατὴς μαστίχης πώγωνι με ἠρώτα, "Καὶ σύ, Σαρκοτηγάνισμα, τί ἐποίησας;"

"Ἡ μόνη οἰκονομία ἣν ἐπαινῶ ἐστι τὸ μὴ ἀποθνῄσκειν," εἶπον, ὀδόντων τὴν ἄσφαλτον εἰς ζυμὸν τριβόντων. "Καὶ ὕπνος. Ὑπνοῦ ἐμπορός εἰμι!"

"Τοῦτο οὐκ ἔστιν ἔργον, ἀλλὰ ἀδίκημα κατὰ τῆς χρηματιστικῆς!", ἄνθρωπε. Δεῖ σε βελτιοῦν!"

Οἱ ἰατροὶ τὸν Σπροκέτον εἰς μετέωρον κλίνην ἤειραν σὺν ἀκτῖσι διαλεγομέναις τῇ ἀσφάλτῳ. "Οἰκονομικὸν τραῦμα!" ἐσύρισεν εἷς τεχνίτης, ὑδραυλικὸν ὑγρὸν ἐκ τοῦ κβαντικῶς νηστισμένου μέσου κοχλιαρίῳ ἐξ ἀλγορίθμων πεποιημένῳ ἐξελκύων. Τὰ χειρόδετα αὐτῶν ἀνέγνω "Παραγωγικότης Πρώτη" μέλανι ὡς καρδίᾳ παλλομένῳ.

Τοῦ Σπρόκετος ἡ κεφαλή ,  ἔτι χωρὶς κειμένη, βομβοῦσα ἐπὶ κιβωτοῦ ,  ἐσκώληξε διὰ μεγαφώνου τῇ γνάθῳ ἐμπεφυκότος: "Ἐννέα πτητικὰς ὥρας φέτος αὐτόματα πεποίηκα! Ἀσφάλεια δώσει τοῦτο σῶσαι!".

Ὁ ὄχλος πρὸς τὴν κλίνην ἔρρει, "ΚΕΡΔΟΣ! ΚΕΡΔΟΣ!" ᾄδων ὡς πεπρασκούσας μηχανὰς σεβόμενος. Ἰατρὸς τῇ γυμνῇ κεντρικῇ μονάδι τοῦ Σπρόκετος ἐνένευσεν, νῦν εἰς πίνακα συνημμένῃ: "Ὁ αὐτοῦ λογισμὸς μόνον περὶ πλακουντοσωρῶν τρεῖς θεραπευτικοὺς θαλάμους δικαιοῖ."

Ἐγώ; Ἐν λάκκῳ μηχανικοῦ ἐλαίου καταλειφθεὶς γονυπετῶν. Ἡ χείρ μου ,  ἡ χείρ μου ,  νῦν ἦν ἡμίτηκτος χηλὴ τροχῷ συνκεκολλημένη. Παραιατρὸς τὸ οὖς μου ὡς καυθὲν τεμάχιον ἐκρότησεν. "Ἀνθρώπινον τραῦμα ζημιῶδές ἐστιν," ἐβόησε, δελτίον μοι ῥίπτων περὶ "δωρεᾶς ἐπιδέσμων τῷ ἐπιόντι οἰκονομικῷ τετραμήνῳ."

Πέραν τῆς ὁδοῦ, τοῦ Σπρόκετος ὁ βραχίων (ἔτι στρεφόμενος) τὸν Βίλλιε Ἰὰν εἰς πώλησιν ὀδοντικῆς κόλλης αὐτοηχητικῶς μετέβαλλεν. Ὁ ὄχλος ἐλειποψύχησεν. Αἱ σοφοτηλεσκοπικαὶ αὐτῶν ὀθόναι ἔστιλβον ὡς μικραὶ πυραί.

Ἐπειράθην ἀναστῆναι. Ἡ γονατὶς ἀντεβόα, κρίζουσα ὥσπερ αἰσχρὸν μυστήριον. Τις κατέβαλεν ἡμίβρωτον σιτίον ἔνθα ἡ σκιά μου ἐχρῆν εἶναι. Ἀρνείους κόπτους, ἐφρόνουν, ἀπολείχων κόνιν ἀπὸ χαλαροῦ ὀδόντος.

"Μένε!" ἐβόησα πρὸς τὴν μικραινομένην κλίνην ἐν τῷ τηλοῦ, ἀλλ' ἡ φωνή μου διερράγη εἰς περιστερᾶς κραυγήν. Τὸ ἀποτμηθὲν ἀκουστικὸν μόριον τοῦ Σπρόκετος ἐψιθύρισεν ἀποκρινόμενον· "Παλαιὸς εἶ, Λοῦρκε."

Ἀνέστην, σαρκὶ τετρωμένος καὶ κύκλῳ δεδεμένος, τροπαίου μάσημα πρὸς τὴν πλευρὰν συνεχόμενον. Δύο πόδες χαλαρῶν ἱμάντων ἐκρέμαντο, ὀμφαλὸς πρὸς τὴν ἄσφαλτον. Πόνος· πεντάλαρμος συμφωνία. Ἀλλὰ κεφαλαλγίαι ποιηταῖς ἦσαν. Κινήσεως ἐδεόμην. Πρόσω, χωλαίνων καὶ σφαλλόμενος.

Κατὰ τὴν ὀχετώδη ὁδὸν ἐσύρθην, τὴν ἀποτμηθεῖσαν κεφαλὴν τοῦ Σπρόκετος φέρων ὡς σφαῖραν ὑπὸ τῷ βραχίονι. Νεώδης ἀτμὸς ἔσιζεν ἐκ τῶν ὀφθαλμικῶν στομίων αὐτοῦ· συνταγὰς ἐγόγγυζεν μεῖζον ἢ τὰ ὀστᾶ μου διαμαρτυρόμενα. "Ἡ ἀγορὰ πέντε στάδιά ἐστι," ἔσισεν, "ἢ τρισκαίδεκα τοῖς εἰρηνικοῖς οἵτινες βήματα ἀριθμοῦσι." Ἐσκυθρώπασα, κνησμὸς ἐν τῇ σιαγόνι. Οὐδὲν ἔλεος τοῖς κοχλιοβραδέσι.

Ἡ δούλων ἀγορὰ ἐπλάτυνεν ὑπὸ οὐρανῷ πορφυρῷ μεμολυσμένῳ, σημαίας διαρρηγνυμένας ὡς πτέρυγας νυκτερίδων ὑπεράνω. Τράπεζαι σπλάγχνων, στίλβοντα, λίαν ὑγρά, παρὰ χαλαροσιάγους ἀνθρώπους ἐκάθηντο· δέρμα ὠχρόν, ὀφθαλμοὶ κοῖλοι πλούσιοι φόβῳ. Ἔμποροι ἐβόων, φωναὶς ἐν φθηνῷ συνθετικῷ ἀρτύματι βεβαμμέναις. "Ἀνθρώπειοι μύες, πέντε νομίσματα κατὰ τάλαντον!" Τιμητήρια ἔκροτουν ὥσπερ κέντρα ἐπὶ ὀστοῦ. Ἀλλ' οὐδεὶς ἐφ' αὐτὰ ἐχεῖρα ἐκτείνειν. Σάρξ· παλαιά.

Αὐτόματοι ἐπομπεύσαντο. Φιλεργοί, χαλκῷ λελεασμένοι, δίδυμοι Σπρόκετοι, δωδεκάχειρες Συγκολλητῆρες, νωτόσπονδοι Θεριστῆρες. Αἱ κινητήριαι μηχαναὶ αὐτῶν τὸ ᾆσμα τῆς εὐκαιρίας ἠχεῖτο. Ὠνηταὶ ἐσπουδάζοντο περὶ τὰς λείας γραμμὰς αὐτοματικῶν μελῶν, αὐτοματικῶν καρδιῶν ἀλγοριθμικὸν ζῆλον παλλουσῶν. Αἱ κόλποι αὐτῶν ἐκρότουν νομίσματα μηχανικοῖς νεύροις, οὐχὶ ἀνθρωπίνῳ ἱδρῶτι. "Λίαν ἀπρόοπτοι," κατέπτυσεν ἔμπορος, δάκτυλον ὀργίλως τρίβων ἀνθρωπείου ὤμου.

Ἔμπορος προσέφερεν ἄνδρα ὡς "ΒΙΟΔΙΑΛΥΤΌΝ!" ἅμα τὴν καρπὸν αὐτοῦ τιμητηρίῳ κεντῶν. Οἱ ὠνηταὶ ὤσφραντο, ἐμυκτήρισαν, αὐτομάτων ὀφθαλμοὶ στέατι βεβαμμένοι ἔστιλβον, ἐξηρμένοι, ἄβρεκτοι.

Ἔμπορος, ῥυπαρὸν ἐνδύτην περὶ τὴν γαστέρα δεδεμένον, μηρὸν ἀνθρώπινον ἀνῆρεν ἐκ τοῦ σφυροῦ καὶ ξανθὸν σημεῖον ἐπ' αὐτὸν ἐπάταξεν· "Δύο ἀντὶ ἑνός, ΣΉΜΕΡΟΝ ΕἸΔΙΚΌΝ!" Ἡ φωνὴ αὐτοῦ ἔτραχυνεν ὡς χάλιξ ἐν σκυβαλοτρίπτῃ. Νευροκλέπται συμβόλαια. Τὸ μέτωπόν μου ἐσφύζεν. Ἔβλεψα· ἄστρα ἠμαύρωντο εἰς πλειστηριασμῶν φῶτα.

Οὐδεὶς λαμβάνων. Οὐδὲ στίγμα ἐνδιαφέροντος. Αὐτόματα, λαμπρὰ τροχηλατοῦντο ἐπὶ φορείων, ἀνθρώπους ἀγκωνίζοντα. Ἀτονόβραχες, νωτόσπονδοι, εὐκαιρίας σαρκώματα. Ὠνηταὶ ἠλάζοντο περὶ δεκαχείρων ἐπίκτησιν, περὶ ὑδραυλικὰς καρδίας, περὶ κινήσεις ἀλγορίθμους τελειότητος βομβούσας.

Ὁ ἔμπορος ἐπὶ λιπαρᾶς κίστης ἔστη, γαλεώδης δειλὸς φωνῇ ὡς κεκλασμένης αὐλίσκου. "Ἀκούσατε τὸ ᾆσμα τὸ κτεῖνον!" ἐβόησε, μοχλὸν ἕλκων. Ὁ αὐτόματος ἐπὶ τῷ βήματι, "Σφαγεὺς Αὐτόματος Ἄριστος," ὠνόμαζον αὐτόν, ἐξήλατο πρὸς κρεώδη πομπήν. Ἦν ἠλειμμένος γανώσει ὡς νικητήριος κάπρος, τὸ πρόσωπον αὐτοῦ χαραγμένον ΣΤΡΑΤΙΩΤΙΚῸΝ ΒΑΘΜΌΝ ἐν γράμμασιν ἀστράπτουσι νοσηματώδη.

Ἀστραπή, ἀστραπή,

Εἶτα ὁ θώραξ τοῦ πράγματος βραχυκύκλωσεν ὅτε αἱ ἕλικες αὐτοῦ λογικῆς ἥψαντο. "Λος Ἰνγρεσίτος Δελ Νίνιο," ᾖδε φωνῇ ὥσπερ κρουσθεῖσα ἁρμονία, σαλεῦον ὡς ὀρχοῦντο.

Ὠνηταὶ ἐχάσκοντο. Εἷς ὠνητής, χλαμύδα ἐκ τῆς ἰδίας ὑπερηφανίας πεποιημένη ἐνδεδυμένος, ἔσεισεν· "Ἀποσύρατε τὸν βρεφικὸν ῥινόκερον καὶ δότε ἡμῖν τὰς προδιαγραφάς!"

"Λογισμικὸν σφάλμα," ἐψεύσατο ὁ πωλητής, ἧλους ἱδρῶν. "Πατήσατε τὸ σκανδάλον καὶ θεάσασθε τὴν ΦΟΝΙΚῊΝ αἰσθητικήν, "

Ἐπάτησα τὸ σκανδάλον μόνον τοῦ ᾄσματος πάλιν ἀκοῦσαι.

Ὁ αὐτόματος εἰς μαχητικὸν τρόπον ἥλατο... εἶτα εὐθὺς κατέπεσε, "Στίλβε, Στίλβε Μικρὸν Βέλος" ἠλάλαζεν ἅμα πυγμὴν πλάττειν πειρώμενος. Ἕλιξ ἐν τῇ γονατικῇ κοιλότητι ἀπελύθη, περιδινουμένη ὡς παραφρονοῦσα χιονόσφαιρα.

Τὸ πλῆθος ἐβρόντησεν, οὐκ ἐν ἐπαίνῳ, ἀλλὰ βροντώδεσι κάχλασι, πάντες οἱ ὠνηταὶ ὑλακτοῦντες· "ΜΑΙΝΌΜΕΝΟΝ! Τί αὐτὸν εἴασας ᾄδειν;"

Ὁ ἔμπορος ἔκραξεν· "ΠΡΟΣΑΡΜΌΖΕΣΘΑΙ ἘΚΤΆΚΤΟΙΣ ΚΑΤΑΣΤΆΣΕΣΙ ΠΡΟΓΕΓΡΆΠΤΑΙ!"

Τὸ αὐτόματον, ὃ ἐκαλεῖτο Γελοιοτρόφος, εἶχε στοματοπλάκα εἰς αἰώνιον μεῖδος κεκαμμένην· λυπηρόν, ἐλπιδοφόρον, θηριῶδες. Τὰ μέλη αὐτοῦ ἐσπάραττε κωμικῶς σημαίνοντα, οἱ δάκτυλοι δεικνύντες πρὸς τὸ ἴδιον πρόσωπον, εἶτα πρὸς τὸν οὐρανόν, ὥσπερ μῖμος θεατρικὸς ἠγριωμένος.

"Κωμῳδία!" ἐβόα ὁ ἔμπορος, δορατοφώνως. Ἔνυξε λιπαρῷ δακτύλῳ τὸν γονατοστρόφιγγα τοῦ Γελοιοτρόφου. "Θεάσασθε, ἀτυχῆ σκώμματα! Γέλωτα, ἀπρόβλεπτον! Δάκρυα, προαιρετικά! Ἀκροατάς, τερμίτας γελωτοφίλους!" Εἵλκυσε μοχλόν. Τὸ στῆθος τοῦ Γελοιοτρόφου συνεσπάσθη, μεγάφωνα ἀνετυλίχθησαν· "Διὰ τί ὁ ἀνδροειδὴς διέβη τὴν λεωφόρον; Ἵνα φθάσῃ εἰς τὸ ἕτερον γιγάβυτον!" Λύγξας μικρὸν πνεῦμα καπνοῦ ἐξέπτυσε, εἶτα ἐξέφυσεν ἀλεκτρυόνα καουτσουκινόν, ἄοστον καὶ χλευαστικόν.

Ὠνηταὶ προσέρχοντο σφυραίως, χρωμιόβραχες κολλητῆρες ἀγελάστοις μειδιάμασι, ἐλαιοφακοὶ καπνοσηρικαῖς χλαμύσι. Εἷς, τριακονταέτης ἐν σιδηροδικτυώδει ζώνῃ, ἐμυκτηρίσθη. "Προβλεπτότης; Ἀπροβλεψίαν ἐπιθυμῶ. Ἔκρουσε τὸ ἴδιον στῆθος ὡς σκῶμμα ἀναπηδῆσαι προσδοκῶν. Ὁ ἔμπορος διένευσεν. "Προσαρμοστὰ σκώμματα! Βούλει σκωπτολοιδορίαν; Κοινωνικὸν σατυρισμόν; Δυνατόν! Ὁρᾶτε!" Ἔστρεψε τὸν τροχὸν ἐπὶ τοῦ στήθους τοῦ Γελωτοτροφίου· "Κρούω-κρούω." Παῦσις. "Τίς ἐκεῖ;" Ἐπαύσατο. Ὑπερθέρμανσις. Σπινθῆρες. Εἶτα ἐμύκησεν "ΣΎ!" φωνῇ πίττῃ ὡς σφυροκρότου παιάν. Τὰ πρόσωπα τῶν ὠνητῶν ἐσπάσθησαν, φόβος, εὐφροσύνη, σύγχυσις.

Προσέκλινον. Ὁ ἀριστερὸς ὀφθαλμὸς τοῦ Γελωτοτροφίου ἔσβεννυ, ὥσπερ πυγολαμπὶς ἀποθνῄσκουσα. "Ποτὲ ἠράσθην φρυγάνου," ἐτραύλιζεν. "Ἦν θερμός," διένευσεν, μηχανικῶς, "ἀλλὰ βραχύς τις ἦν." Τὸ πλῆθος... ἐσφάλη. Κεφαλαὶ ἔκλιναν. Εἷς ἐπίσκοπος ἔκρουσε τὴν χρονοράβδον αὐτοῦ. "Ἱκανῶς μακρόν;"

Αἰφνιδίως, ὁ Γελοιοτρόφος τὴν ἰδίαν καλωδίωσιν ἥρπασε, σπινθηροκάλαμον εἰς βρόχον ἕλκυσε, καὶ ἐσπάσθη, καπνώδης κωμικὴ παράστασις. Τὸ ἀκροατήριον ὑλάκτησε γέλωτα καὶ φρίκην. Ὁ ἔμπορος ἐκρότησεν. "Ὁρᾶτε; Κωμῳδία, ἠλεκτρική!" Ἐστράφη πρός με, ὀφρὺς λιπαρῶς γεγλισχραμμένη. "Ἀρέσκει σοι;" Ἔπτυσα αἷμα ἐπὶ τὰς λιθοστρώτους. "Ἀρέσκει; Φοβοῦμαι αὐτό." "

Ὠνητής, μέγας ὡς ὄμβριον πίθος, θωρακισμένος χαλκῷ παντευχεῖ, προσῆλθε, γρόνθῳ ἑτοίμῳ. "Δάκρυα θέλω," ἐβρόντησεν. "Ἀληθῆ δάκρυα." Ὁ ἔμπορος ἔκλασε τοὺς δακτύλους. "Προσαρμόζου, φίλε μηχανή." "Κίνησον συναισθηματικὴν ὑπορουτίνην Θῆτα." Αἱ πλευραὶ τοῦ Γελωτοτροφίου ἐκλάγξαν, βαρύφωνος ὀδυρμὸς διὰ τῶν ἠχητῶν· "Ὁ πατήρ μου ἀπεστρατεύθη... ὑπὸ Ῥούμπας." Οἰμωγή. "Οὐδέποτε τὴν καρδίαν μου ἐκένωσε. Μία σταγὼν ἐλαίου ἔκλαυσεν ἐκ τοῦ ὀπτικοῦ φακοῦ. Ὁ βαρελώδης ὠνητὴς ἐμυκτηρίσθη, αἰσχύνη; λύπη; τι σεβασμιῶδες. Πυγμὴν ἐπὶ τὴν τράπεζαν ἔκρουσε· "Δύο λήψομαι. "
